#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TEMPLATE_ROOT="$ROOT_DIR/template"
TEMPLATE_VERSION_FILE="$ROOT_DIR/VERSION"
ADDON_ROOT_DEFAULT="$ROOT_DIR/packs"
ADDON_ROOT="${AI_DEV_TEMPLATE_ADDON_ROOT:-$ADDON_ROOT_DEFAULT}"

usage() {
  cat <<EOF
Usage:
  ./scripts/setup/scaffold.sh <target_dir> [--with pack1,pack2]

Example:
  ./scripts/setup/scaffold.sh /path/to/new-project --with problem-first

Generation is transactional: everything is built in a temporary staging
directory first, and only moved into <target_dir> once every step (base
copy, pack application, metadata write) succeeds. A failure at any point
leaves no partial <target_dir> behind.
EOF
}

if [[ $# -lt 1 ]]; then
  usage
  exit 1
fi

TARGET_DIR=""
PACKS=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --with)
      PACKS="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      if [[ -z "$TARGET_DIR" ]]; then
        TARGET_DIR="$1"
      else
        echo "[error] unexpected argument: $1" >&2
        exit 1
      fi
      shift
      ;;
  esac
done

if [[ -z "$TARGET_DIR" ]]; then
  echo "[error] target_dir is required" >&2
  exit 1
fi

if [[ -e "$TARGET_DIR" ]]; then
  echo "[error] target already exists: $TARGET_DIR" >&2
  exit 1
fi

if [[ ! -d "$TEMPLATE_ROOT" ]]; then
  echo "[error] template root not found: $TEMPLATE_ROOT" >&2
  exit 1
fi

if [[ ! -d "$ADDON_ROOT" ]]; then
  echo "[error] pack root not found: $ADDON_ROOT" >&2
  echo "Set AI_DEV_TEMPLATE_ADDON_ROOT or create packs under $ROOT_DIR/packs" >&2
  exit 1
fi

# Build everything in a temporary staging directory first. set -e means any
# failure below (missing pack manifest, missing append-target file, etc.)
# aborts immediately and the trap cleans up -- $TARGET_DIR is only ever
# touched by the final move at the very end, once every step has succeeded.
STAGE_DIR="$(mktemp -d "${TMPDIR:-/tmp}/ai-dev-template.XXXXXX")"
trap 'rm -rf "$STAGE_DIR"' EXIT

copy_base_template() {
  local source_dir="$1"
  local dest_dir="$2"

  local entries=()
  while IFS= read -r entry; do
    entries+=("$entry")
  done < <(find "$source_dir" -mindepth 1 -maxdepth 1 \
    ! -name '.DS_Store' \
    ! -name '.git' \
    ! -name 'memory' \
    -print | sort)

  # bash 3.2 (macOS's stock /bin/bash) treats "${arr[@]}" on a declared-but-
  # never-populated array as an unbound variable under set -u; ":-" avoids
  # that crash if $source_dir ever has zero top-level entries.
  for entry in "${entries[@]:-}"; do
    if [[ -n "$entry" ]]; then
      cp -R "$entry" "$dest_dir/"
    fi
  done

  mkdir -p "$dest_dir/memory"
  cp -R "$source_dir/memory/README.md" "$dest_dir/memory/"
  cp -R "$source_dir/memory/current-state.md" "$dest_dir/memory/"
  cp -R "$source_dir/memory/decisions.md" "$dest_dir/memory/"
  cp -R "$source_dir/memory/tasks.md" "$dest_dir/memory/"
  mkdir -p "$dest_dir/memory/sessions"
  touch "$dest_dir/memory/sessions/.gitkeep"
  if [[ -f "$source_dir/.gitignore" ]]; then
    cp "$source_dir/.gitignore" "$dest_dir/.gitignore"
  fi
  find "$dest_dir" -name '.DS_Store' -delete
}

# Name:version of every pack actually applied, in application order --
# collected here so the metadata file below reports versions read from
# each pack's own manifest, rather than duplicating them by hand.
APPLIED_PACKS=()

apply_pack() {
  local pack_name="$1"
  local pack_dir="$ADDON_ROOT/$pack_name"
  local manifest="$pack_dir/pack-manifest.sh"

  if [[ ! -f "$manifest" ]]; then
    echo "[error] pack manifest not found: $manifest" >&2
    exit 1
  fi

  # shellcheck source=/dev/null
  source "$manifest"

  local merge_dir="$pack_dir/$PACK_MERGE_DIR"
  local append_dir="$pack_dir/$PACK_APPEND_DIR"

  if [[ -d "$merge_dir" ]]; then
    while IFS= read -r file; do
      local rel_path="${file#$merge_dir/}"
      mkdir -p "$STAGE_DIR/$(dirname "$rel_path")"
      cp "$file" "$STAGE_DIR/$rel_path"
      if [[ "$file" == *.sh ]]; then
        chmod +x "$STAGE_DIR/$rel_path"
      fi
    done < <(find "$merge_dir" -type f | sort)
  fi

  if [[ -d "$append_dir" ]]; then
    while IFS= read -r fragment; do
      local rel_path="${fragment#$append_dir/}"
      local target_file="$STAGE_DIR/$rel_path"
      if [[ ! -f "$target_file" ]]; then
        echo "[error] append target missing: $rel_path" >&2
        exit 1
      fi
      {
        echo
        echo
        cat "$fragment"
      } >> "$target_file"
    done < <(find "$append_dir" -type f | sort)
  fi

  find "$STAGE_DIR" -name '.DS_Store' -delete

  APPLIED_PACKS+=("$pack_name:$PACK_VERSION")
}

write_metadata() {
  local dest_dir="$1"
  local profile_label="${AI_DEV_TEMPLATE_PROFILE:-custom}"
  local template_version="unknown"
  if [[ -f "$TEMPLATE_VERSION_FILE" ]]; then
    template_version="$(cat "$TEMPLATE_VERSION_FILE")"
  fi
  local created_at
  created_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

  {
    echo "# Generated by AI_dev_template -- do not hand-edit; regenerate"
    echo "# instead if you need a different template_version/profile/packs."
    echo "schema_version: 1"
    echo "template_version: $template_version"
    echo "profile: $profile_label"
    if [[ "${#APPLIED_PACKS[@]}" -eq 0 ]]; then
      echo "installed_packs: {}"
    else
      echo "installed_packs:"
      local entry name version
      for entry in "${APPLIED_PACKS[@]}"; do
        name="${entry%%:*}"
        version="${entry#*:}"
        echo "  $name: $version"
      done
    fi
    echo "created_at: \"$created_at\""
  } > "$dest_dir/.ai-dev-template.yml"
}

echo "== Scaffold Project =="
echo "base: $TEMPLATE_ROOT"
echo "target: $TARGET_DIR"
echo "pack root: $ADDON_ROOT"

copy_base_template "$TEMPLATE_ROOT" "$STAGE_DIR"

if [[ -n "$PACKS" ]]; then
  IFS=',' read -r -a pack_list <<< "$PACKS"
  for pack in "${pack_list[@]}"; do
    trimmed_pack="$(printf '%s' "$pack" | sed 's/^ *//;s/ *$//')"
    if [[ -z "$trimmed_pack" ]]; then
      continue
    fi

    # Skip a pack already applied earlier in the same run (e.g. the same
    # name listed twice in --with) -- merge/ re-copies would be harmless,
    # but append/ fragments would otherwise be duplicated into the target.
    already_applied=false
    for applied in "${APPLIED_PACKS[@]:-}"; do
      if [[ "${applied%%:*}" == "$trimmed_pack" ]]; then
        already_applied=true
        break
      fi
    done
    if [[ "$already_applied" == true ]]; then
      echo "[pack] $trimmed_pack (already applied, skipping duplicate)"
      continue
    fi

    echo "[pack] $trimmed_pack"
    apply_pack "$trimmed_pack"
  done
fi

write_metadata "$STAGE_DIR"

# Re-check immediately before the one irreversible step, not just at
# argument-parsing time -- and never overwrite an existing target.
if [[ -e "$TARGET_DIR" ]]; then
  echo "[error] target already exists: $TARGET_DIR" >&2
  exit 1
fi
mkdir -p "$(dirname "$TARGET_DIR")"
if mv "$STAGE_DIR" "$TARGET_DIR" 2>/dev/null; then
  :
else
  # Cross-filesystem fallback: mktemp's directory is frequently a different
  # filesystem/tmpfs than the target (common on Linux), where a plain mv
  # across devices fails.
  mkdir -p "$TARGET_DIR"
  cp -R "$STAGE_DIR/." "$TARGET_DIR/"
  rm -rf "$STAGE_DIR"
fi

echo
echo "Scaffold complete."
echo "Next steps:"
echo "- cd \"$TARGET_DIR\""
echo "- ./scripts/setup/doctor.sh"
echo "- ./scripts/setup/bootstrap.sh"
